import type { Blog } from "@/common/blog/blog";
import { backgradProject } from "@/data/backrand/backrand";
import { createProjectRelation } from "@/lib/relations";
import Content from "./content.mdx";

export const backgradSystemBlog: Blog = {
  id: "backgrad-generative-gradient-system",
  title: "Building a generative gradient system",
  subtitle:
    "How Backgrad turns palettes, layout fields, and export rules into repeatable visual assets.",
  tagline: "Repeatable backgrounds, not one-off images",
  summary:
    "A technical note on the Backgrad rendering pipeline, the constraints behind useful generated backgrounds, and how presets keep creative output editable.",
  Content,
  readingTime: 7,
  tags: ["Backgrad", "Generative design", "Rendering", "Design tools"],
  category: "Design systems",
  status: "Published",
  featured: true,
  audience: "Designers and developers exploring generated interface assets.",
  projectId: backgradProject.id,
  heroImage: {
    src: "/images/backrand/exp10_organic_layout.png",
    alt: "Organic warm gradient generated with Backgrad",
    caption: "Generated by Backgrad. Credit: Lukas Olsen.",
  },
  keyTakeaways: [
    "Backgrad treats backgrounds as reproducible render recipes.",
    "The pipeline separates presets, palette logic, layout, effects, and export.",
    "Useful output is judged by how well it survives text overlays and cropping.",
  ],
  type: "personal",
  relations: [createProjectRelation(backgradProject)],
  created_at: new Date("2026-02-04T10:00:00Z").toISOString(),
  updated_at: new Date("2026-02-04T10:00:00Z").toISOString(),
};
