import { useState, useCallback, useEffect } from "react";
import { createFileRoute } from "@tanstack/react-router";
import { motion } from "framer-motion";
import { backrandProject } from "@/data/backrand/backrand";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { ChevronLeft, ChevronRight, ImageOff, ArrowLeft } from "lucide-react";

export const Route = createFileRoute("/lab/backgrad-gallery")({
  component: GalleryPage,
});

function GalleryPage() {
  const images = backrandProject.gallery?.images ?? [];
  const [openIndex, setOpenIndex] = useState<number | null>(null);
  const [loaded, setLoaded] = useState<Set<number>>(new Set());
  const [failed, setFailed] = useState<Set<number>>(new Set());

  const handleLoad = (i: number) => setLoaded((prev) => new Set(prev).add(i));
  const handleFail = (i: number) => setFailed((prev) => new Set(prev).add(i));

  const goNext = useCallback(() => {
    setOpenIndex((prev) => (prev === null ? null : (prev + 1) % images.length));
  }, [images.length]);

  const goPrev = useCallback(() => {
    setOpenIndex((prev) => (prev === null ? null : (prev - 1 + images.length) % images.length));
  }, [images.length]);

  useEffect(() => {
    if (openIndex === null) return;
    const onKey = (e: KeyboardEvent) => {
      if (e.key === "ArrowRight") goNext();
      if (e.key === "ArrowLeft") goPrev();
      if (e.key === "Escape") setOpenIndex(null);
    };
    window.addEventListener("keydown", onKey);
    return () => window.removeEventListener("keydown", onKey);
  }, [openIndex, goNext, goPrev]);

  const openImage = openIndex !== null ? images[openIndex] : null;

  return (
    <div className="min-h-screen w-full bg-background text-foreground">
      <div className="max-w-6xl mx-auto px-4 md:px-8 py-12">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5 }}
          className="space-y-10"
        >
          <div className="space-y-4">
            <a
              href="/lab/backgrad"
              className="group inline-flex items-center gap-1.5 text-xs text-muted-foreground hover:text-foreground transition-colors"
            >
              <ArrowLeft className="w-3 h-3 group-hover:-translate-x-0.5 transition-transform" />
              Back to Backgrad
            </a>

            <div className="space-y-2">
              <h1 className="text-3xl font-bold tracking-tight text-foreground">
                Gallery
              </h1>
              <p className="text-[15px] text-muted-foreground leading-relaxed max-w-2xl">
                All images generated by Backgrad. No manual editing, no external tools.
                Every pixel computed from code.
              </p>
              <p className="text-xs text-muted-foreground/50">
                {images.length} images · Click any image to view full size
              </p>
            </div>
          </div>

          <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-2">
            {images.map((image, i) => (
              <motion.figure
                key={i}
                initial={{ opacity: 0, y: 12 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.3, delay: i * 0.04 }}
                className="group relative aspect-[4/3] overflow-hidden rounded-lg bg-muted/30 border border-border/15 cursor-pointer"
                onClick={() => setOpenIndex(i)}
              >
                {!loaded.has(i) && !failed.has(i) && (
                  <div className="absolute inset-0 bg-muted/30 animate-pulse" />
                )}
                {failed.has(i) ? (
                  <div className="absolute inset-0 flex flex-col items-center justify-center bg-muted/10">
                    <ImageOff className="w-6 h-6 text-muted-foreground/40 mb-1" />
                    <span className="text-[10px] text-muted-foreground/40">Failed to load</span>
                  </div>
                ) : (
                  <img
                    src={image.src}
                    alt={image.alt}
                    loading="lazy"
                    decoding="async"
                    onLoad={() => handleLoad(i)}
                    onError={() => handleFail(i)}
                    className={`w-full h-full object-cover transition-all duration-500 group-hover:scale-105 ${
                      loaded.has(i) ? "opacity-100" : "opacity-0"
                    }`}
                  />
                )}

                <div className="absolute inset-0 bg-gradient-to-t from-background/60 via-transparent to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-300" />

                <div className="absolute top-2 right-2">
                  <span className="inline-flex items-center px-1.5 py-0.5 rounded bg-background/80 backdrop-blur-sm text-[9px] font-mono text-muted-foreground border border-border/20">
                    Generated
                  </span>
                </div>

                <div className="absolute bottom-0 left-0 right-0 p-2.5 opacity-0 group-hover:opacity-100 transition-opacity duration-300">
                  <p className="text-[11px] text-foreground/80 leading-snug truncate">
                    {image.caption || image.alt}
                  </p>
                </div>
              </motion.figure>
            ))}
          </div>

          <div className="pt-8 border-t border-border/20">
            <p className="text-[12px] text-muted-foreground/40 text-center">
              All images © Lukas Olsen · Generated with Backgrad
            </p>
          </div>
        </motion.div>
      </div>

      <Dialog
        open={openIndex !== null}
        onOpenChange={() => setOpenIndex(null)}
      >
        {openImage && (
          <DialogContent className="p-0 overflow-hidden bg-background/90 backdrop-blur-lg border border-border/40 max-w-5xl shadow-lg rounded-xl">
            <DialogHeader>
              <DialogTitle className="p-5 text-lg font-semibold text-foreground flex items-center justify-between">
                <span>{openImage.alt}</span>
                <span className="text-sm font-normal text-muted-foreground">
                  {openIndex !== null && `${openIndex + 1} / ${images.length}`}
                </span>
              </DialogTitle>
            </DialogHeader>

            <div className="relative group/lb">
              <img
                src={openImage.src}
                alt={openImage.alt}
                className="w-full h-auto object-contain max-h-[70vh]"
              />

              <button
                onClick={(e) => { e.stopPropagation(); goPrev(); }}
                className="absolute left-3 top-1/2 -translate-y-1/2 w-10 h-10 rounded-full bg-background/80 backdrop-blur-sm border border-border/40 flex items-center justify-center opacity-0 group-hover/lb:opacity-100 transition-opacity hover:bg-background/95"
              >
                <ChevronLeft className="w-5 h-5" />
              </button>
              <button
                onClick={(e) => { e.stopPropagation(); goNext(); }}
                className="absolute right-3 top-1/2 -translate-y-1/2 w-10 h-10 rounded-full bg-background/80 backdrop-blur-sm border border-border/40 flex items-center justify-center opacity-0 group-hover/lb:opacity-100 transition-opacity hover:bg-background/95"
              >
                <ChevronRight className="w-5 h-5" />
              </button>
            </div>

            {(openImage.caption || openImage.credit) && (
              <div className="p-5 text-center text-sm leading-relaxed text-foreground bg-background/80 backdrop-blur-md border-t border-border/40 rounded-b-xl">
                {openImage.caption && (
                  <p className="font-medium text-base">{openImage.caption}</p>
                )}
                {openImage.credit && (
                  <p className="text-xs mt-2 text-muted-foreground">
                    © {openImage.credit} · Generated by Backgrad
                  </p>
                )}
              </div>
            )}
          </DialogContent>
        )}
      </Dialog>
    </div>
  );
}
