/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogsDotxmlRouteImport } from './routes/blogs[.]xml'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogsIndexRouteImport } from './routes/blogs/index'
import { Route as ProjectsDyplinkAiRouteImport } from './routes/projects/dyplink-ai'
import { Route as LabBackrand6RouteImport } from './routes/lab/backrand-6'
import { Route as BlogsIdRouteImport } from './routes/blogs/$id'
import { Route as ApiProjectsRouteImport } from './routes/api/projects'
import { Route as ApiBlogsRouteImport } from './routes/api/blogs'
import { Route as ProjectsBackrandIndexRouteImport } from './routes/projects/backrand/index'
import { Route as ProjectsBackgradIndexRouteImport } from './routes/projects/backgrad/index'
import { Route as ProjectsBackrandPlaygroundRouteImport } from './routes/projects/backrand/playground'
import { Route as ProjectsBackgradGalleryRouteImport } from './routes/projects/backgrad/gallery'

const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsDotxmlRoute = BlogsDotxmlRouteImport.update({
  id: '/blogs.xml',
  path: '/blogs.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsIndexRoute = BlogsIndexRouteImport.update({
  id: '/blogs/',
  path: '/blogs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsDyplinkAiRoute = ProjectsDyplinkAiRouteImport.update({
  id: '/projects/dyplink-ai',
  path: '/projects/dyplink-ai',
  getParentRoute: () => rootRouteImport,
} as any)
const LabBackrand6Route = LabBackrand6RouteImport.update({
  id: '/lab/backrand-6',
  path: '/lab/backrand-6',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsIdRoute = BlogsIdRouteImport.update({
  id: '/blogs/$id',
  path: '/blogs/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProjectsRoute = ApiProjectsRouteImport.update({
  id: '/api/projects',
  path: '/api/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBlogsRoute = ApiBlogsRouteImport.update({
  id: '/api/blogs',
  path: '/api/blogs',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsBackrandIndexRoute = ProjectsBackrandIndexRouteImport.update({
  id: '/projects/backrand/',
  path: '/projects/backrand/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsBackgradIndexRoute = ProjectsBackgradIndexRouteImport.update({
  id: '/projects/backgrad/',
  path: '/projects/backgrad/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsBackrandPlaygroundRoute =
  ProjectsBackrandPlaygroundRouteImport.update({
    id: '/projects/backrand/playground',
    path: '/projects/backrand/playground',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectsBackgradGalleryRoute = ProjectsBackgradGalleryRouteImport.update({
  id: '/projects/backgrad/gallery',
  path: '/projects/backgrad/gallery',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blogs.xml': typeof BlogsDotxmlRoute
  '/contact': typeof ContactRoute
  '/api/blogs': typeof ApiBlogsRoute
  '/api/projects': typeof ApiProjectsRoute
  '/blogs/$id': typeof BlogsIdRoute
  '/lab/backrand-6': typeof LabBackrand6Route
  '/projects/dyplink-ai': typeof ProjectsDyplinkAiRoute
  '/blogs/': typeof BlogsIndexRoute
  '/projects/backgrad/gallery': typeof ProjectsBackgradGalleryRoute
  '/projects/backrand/playground': typeof ProjectsBackrandPlaygroundRoute
  '/projects/backgrad/': typeof ProjectsBackgradIndexRoute
  '/projects/backrand/': typeof ProjectsBackrandIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blogs.xml': typeof BlogsDotxmlRoute
  '/contact': typeof ContactRoute
  '/api/blogs': typeof ApiBlogsRoute
  '/api/projects': typeof ApiProjectsRoute
  '/blogs/$id': typeof BlogsIdRoute
  '/lab/backrand-6': typeof LabBackrand6Route
  '/projects/dyplink-ai': typeof ProjectsDyplinkAiRoute
  '/blogs': typeof BlogsIndexRoute
  '/projects/backgrad/gallery': typeof ProjectsBackgradGalleryRoute
  '/projects/backrand/playground': typeof ProjectsBackrandPlaygroundRoute
  '/projects/backgrad': typeof ProjectsBackgradIndexRoute
  '/projects/backrand': typeof ProjectsBackrandIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blogs.xml': typeof BlogsDotxmlRoute
  '/contact': typeof ContactRoute
  '/api/blogs': typeof ApiBlogsRoute
  '/api/projects': typeof ApiProjectsRoute
  '/blogs/$id': typeof BlogsIdRoute
  '/lab/backrand-6': typeof LabBackrand6Route
  '/projects/dyplink-ai': typeof ProjectsDyplinkAiRoute
  '/blogs/': typeof BlogsIndexRoute
  '/projects/backgrad/gallery': typeof ProjectsBackgradGalleryRoute
  '/projects/backrand/playground': typeof ProjectsBackrandPlaygroundRoute
  '/projects/backgrad/': typeof ProjectsBackgradIndexRoute
  '/projects/backrand/': typeof ProjectsBackrandIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blogs.xml'
    | '/contact'
    | '/api/blogs'
    | '/api/projects'
    | '/blogs/$id'
    | '/lab/backrand-6'
    | '/projects/dyplink-ai'
    | '/blogs/'
    | '/projects/backgrad/gallery'
    | '/projects/backrand/playground'
    | '/projects/backgrad/'
    | '/projects/backrand/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blogs.xml'
    | '/contact'
    | '/api/blogs'
    | '/api/projects'
    | '/blogs/$id'
    | '/lab/backrand-6'
    | '/projects/dyplink-ai'
    | '/blogs'
    | '/projects/backgrad/gallery'
    | '/projects/backrand/playground'
    | '/projects/backgrad'
    | '/projects/backrand'
  id:
    | '__root__'
    | '/'
    | '/blogs.xml'
    | '/contact'
    | '/api/blogs'
    | '/api/projects'
    | '/blogs/$id'
    | '/lab/backrand-6'
    | '/projects/dyplink-ai'
    | '/blogs/'
    | '/projects/backgrad/gallery'
    | '/projects/backrand/playground'
    | '/projects/backgrad/'
    | '/projects/backrand/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogsDotxmlRoute: typeof BlogsDotxmlRoute
  ContactRoute: typeof ContactRoute
  ApiBlogsRoute: typeof ApiBlogsRoute
  ApiProjectsRoute: typeof ApiProjectsRoute
  BlogsIdRoute: typeof BlogsIdRoute
  LabBackrand6Route: typeof LabBackrand6Route
  ProjectsDyplinkAiRoute: typeof ProjectsDyplinkAiRoute
  BlogsIndexRoute: typeof BlogsIndexRoute
  ProjectsBackgradGalleryRoute: typeof ProjectsBackgradGalleryRoute
  ProjectsBackrandPlaygroundRoute: typeof ProjectsBackrandPlaygroundRoute
  ProjectsBackgradIndexRoute: typeof ProjectsBackgradIndexRoute
  ProjectsBackrandIndexRoute: typeof ProjectsBackrandIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs.xml': {
      id: '/blogs.xml'
      path: '/blogs.xml'
      fullPath: '/blogs.xml'
      preLoaderRoute: typeof BlogsDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/': {
      id: '/blogs/'
      path: '/blogs'
      fullPath: '/blogs/'
      preLoaderRoute: typeof BlogsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/dyplink-ai': {
      id: '/projects/dyplink-ai'
      path: '/projects/dyplink-ai'
      fullPath: '/projects/dyplink-ai'
      preLoaderRoute: typeof ProjectsDyplinkAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab/backrand-6': {
      id: '/lab/backrand-6'
      path: '/lab/backrand-6'
      fullPath: '/lab/backrand-6'
      preLoaderRoute: typeof LabBackrand6RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/$id': {
      id: '/blogs/$id'
      path: '/blogs/$id'
      fullPath: '/blogs/$id'
      preLoaderRoute: typeof BlogsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/projects': {
      id: '/api/projects'
      path: '/api/projects'
      fullPath: '/api/projects'
      preLoaderRoute: typeof ApiProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/blogs': {
      id: '/api/blogs'
      path: '/api/blogs'
      fullPath: '/api/blogs'
      preLoaderRoute: typeof ApiBlogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/backrand/': {
      id: '/projects/backrand/'
      path: '/projects/backrand'
      fullPath: '/projects/backrand/'
      preLoaderRoute: typeof ProjectsBackrandIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/backgrad/': {
      id: '/projects/backgrad/'
      path: '/projects/backgrad'
      fullPath: '/projects/backgrad/'
      preLoaderRoute: typeof ProjectsBackgradIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/backrand/playground': {
      id: '/projects/backrand/playground'
      path: '/projects/backrand/playground'
      fullPath: '/projects/backrand/playground'
      preLoaderRoute: typeof ProjectsBackrandPlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/backgrad/gallery': {
      id: '/projects/backgrad/gallery'
      path: '/projects/backgrad/gallery'
      fullPath: '/projects/backgrad/gallery'
      preLoaderRoute: typeof ProjectsBackgradGalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogsDotxmlRoute: BlogsDotxmlRoute,
  ContactRoute: ContactRoute,
  ApiBlogsRoute: ApiBlogsRoute,
  ApiProjectsRoute: ApiProjectsRoute,
  BlogsIdRoute: BlogsIdRoute,
  LabBackrand6Route: LabBackrand6Route,
  ProjectsDyplinkAiRoute: ProjectsDyplinkAiRoute,
  BlogsIndexRoute: BlogsIndexRoute,
  ProjectsBackgradGalleryRoute: ProjectsBackgradGalleryRoute,
  ProjectsBackrandPlaygroundRoute: ProjectsBackrandPlaygroundRoute,
  ProjectsBackgradIndexRoute: ProjectsBackgradIndexRoute,
  ProjectsBackrandIndexRoute: ProjectsBackrandIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
