/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsDyplinkAiRouteImport } from './routes/projects/dyplink-ai'
import { Route as ProjectsBackrandIndexRouteImport } from './routes/projects/backrand/index'
import { Route as ProjectsBackrandPlaygroundRouteImport } from './routes/projects/backrand/playground'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsDyplinkAiRoute = ProjectsDyplinkAiRouteImport.update({
  id: '/projects/dyplink-ai',
  path: '/projects/dyplink-ai',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsBackrandIndexRoute = ProjectsBackrandIndexRouteImport.update({
  id: '/projects/backrand/',
  path: '/projects/backrand/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsBackrandPlaygroundRoute =
  ProjectsBackrandPlaygroundRouteImport.update({
    id: '/projects/backrand/playground',
    path: '/projects/backrand/playground',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/projects/dyplink-ai': typeof ProjectsDyplinkAiRoute
  '/projects/backrand/playground': typeof ProjectsBackrandPlaygroundRoute
  '/projects/backrand': typeof ProjectsBackrandIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/projects/dyplink-ai': typeof ProjectsDyplinkAiRoute
  '/projects/backrand/playground': typeof ProjectsBackrandPlaygroundRoute
  '/projects/backrand': typeof ProjectsBackrandIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/projects/dyplink-ai': typeof ProjectsDyplinkAiRoute
  '/projects/backrand/playground': typeof ProjectsBackrandPlaygroundRoute
  '/projects/backrand/': typeof ProjectsBackrandIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/projects/dyplink-ai'
    | '/projects/backrand/playground'
    | '/projects/backrand'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/projects/dyplink-ai'
    | '/projects/backrand/playground'
    | '/projects/backrand'
  id:
    | '__root__'
    | '/'
    | '/projects/dyplink-ai'
    | '/projects/backrand/playground'
    | '/projects/backrand/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProjectsDyplinkAiRoute: typeof ProjectsDyplinkAiRoute
  ProjectsBackrandPlaygroundRoute: typeof ProjectsBackrandPlaygroundRoute
  ProjectsBackrandIndexRoute: typeof ProjectsBackrandIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/dyplink-ai': {
      id: '/projects/dyplink-ai'
      path: '/projects/dyplink-ai'
      fullPath: '/projects/dyplink-ai'
      preLoaderRoute: typeof ProjectsDyplinkAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/backrand/': {
      id: '/projects/backrand/'
      path: '/projects/backrand'
      fullPath: '/projects/backrand'
      preLoaderRoute: typeof ProjectsBackrandIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/backrand/playground': {
      id: '/projects/backrand/playground'
      path: '/projects/backrand/playground'
      fullPath: '/projects/backrand/playground'
      preLoaderRoute: typeof ProjectsBackrandPlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProjectsDyplinkAiRoute: ProjectsDyplinkAiRoute,
  ProjectsBackrandPlaygroundRoute: ProjectsBackrandPlaygroundRoute,
  ProjectsBackrandIndexRoute: ProjectsBackrandIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
