/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsDyplinkAiRouteImport } from './routes/projects/dyplink-ai'
import { Route as BlogsIdRouteImport } from './routes/blogs/$id'
import { Route as ApiProjectsRouteImport } from './routes/api/projects'
import { Route as ApiBlogsRouteImport } from './routes/api/blogs'
import { Route as ProjectsBackrandIndexRouteImport } from './routes/projects/backrand/index'
import { Route as ProjectsBackrandPlaygroundRouteImport } from './routes/projects/backrand/playground'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsDyplinkAiRoute = ProjectsDyplinkAiRouteImport.update({
  id: '/projects/dyplink-ai',
  path: '/projects/dyplink-ai',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsIdRoute = BlogsIdRouteImport.update({
  id: '/blogs/$id',
  path: '/blogs/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProjectsRoute = ApiProjectsRouteImport.update({
  id: '/api/projects',
  path: '/api/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBlogsRoute = ApiBlogsRouteImport.update({
  id: '/api/blogs',
  path: '/api/blogs',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsBackrandIndexRoute = ProjectsBackrandIndexRouteImport.update({
  id: '/projects/backrand/',
  path: '/projects/backrand/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsBackrandPlaygroundRoute =
  ProjectsBackrandPlaygroundRouteImport.update({
    id: '/projects/backrand/playground',
    path: '/projects/backrand/playground',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/blogs': typeof ApiBlogsRoute
  '/api/projects': typeof ApiProjectsRoute
  '/blogs/$id': typeof BlogsIdRoute
  '/projects/dyplink-ai': typeof ProjectsDyplinkAiRoute
  '/projects/backrand/playground': typeof ProjectsBackrandPlaygroundRoute
  '/projects/backrand/': typeof ProjectsBackrandIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/blogs': typeof ApiBlogsRoute
  '/api/projects': typeof ApiProjectsRoute
  '/blogs/$id': typeof BlogsIdRoute
  '/projects/dyplink-ai': typeof ProjectsDyplinkAiRoute
  '/projects/backrand/playground': typeof ProjectsBackrandPlaygroundRoute
  '/projects/backrand': typeof ProjectsBackrandIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/blogs': typeof ApiBlogsRoute
  '/api/projects': typeof ApiProjectsRoute
  '/blogs/$id': typeof BlogsIdRoute
  '/projects/dyplink-ai': typeof ProjectsDyplinkAiRoute
  '/projects/backrand/playground': typeof ProjectsBackrandPlaygroundRoute
  '/projects/backrand/': typeof ProjectsBackrandIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/blogs'
    | '/api/projects'
    | '/blogs/$id'
    | '/projects/dyplink-ai'
    | '/projects/backrand/playground'
    | '/projects/backrand/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/blogs'
    | '/api/projects'
    | '/blogs/$id'
    | '/projects/dyplink-ai'
    | '/projects/backrand/playground'
    | '/projects/backrand'
  id:
    | '__root__'
    | '/'
    | '/api/blogs'
    | '/api/projects'
    | '/blogs/$id'
    | '/projects/dyplink-ai'
    | '/projects/backrand/playground'
    | '/projects/backrand/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiBlogsRoute: typeof ApiBlogsRoute
  ApiProjectsRoute: typeof ApiProjectsRoute
  BlogsIdRoute: typeof BlogsIdRoute
  ProjectsDyplinkAiRoute: typeof ProjectsDyplinkAiRoute
  ProjectsBackrandPlaygroundRoute: typeof ProjectsBackrandPlaygroundRoute
  ProjectsBackrandIndexRoute: typeof ProjectsBackrandIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/dyplink-ai': {
      id: '/projects/dyplink-ai'
      path: '/projects/dyplink-ai'
      fullPath: '/projects/dyplink-ai'
      preLoaderRoute: typeof ProjectsDyplinkAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/$id': {
      id: '/blogs/$id'
      path: '/blogs/$id'
      fullPath: '/blogs/$id'
      preLoaderRoute: typeof BlogsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/projects': {
      id: '/api/projects'
      path: '/api/projects'
      fullPath: '/api/projects'
      preLoaderRoute: typeof ApiProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/blogs': {
      id: '/api/blogs'
      path: '/api/blogs'
      fullPath: '/api/blogs'
      preLoaderRoute: typeof ApiBlogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/backrand/': {
      id: '/projects/backrand/'
      path: '/projects/backrand'
      fullPath: '/projects/backrand/'
      preLoaderRoute: typeof ProjectsBackrandIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/backrand/playground': {
      id: '/projects/backrand/playground'
      path: '/projects/backrand/playground'
      fullPath: '/projects/backrand/playground'
      preLoaderRoute: typeof ProjectsBackrandPlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiBlogsRoute: ApiBlogsRoute,
  ApiProjectsRoute: ApiProjectsRoute,
  BlogsIdRoute: BlogsIdRoute,
  ProjectsDyplinkAiRoute: ProjectsDyplinkAiRoute,
  ProjectsBackrandPlaygroundRoute: ProjectsBackrandPlaygroundRoute,
  ProjectsBackrandIndexRoute: ProjectsBackrandIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
